//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.Xml.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class testrun
    {
        public string guid { get; set; }
        public int testcasecount { get; set; }
        public string result { get; set; }
        public int passed { get; set; }
        public int failed { get; set; }
        public int inconclusive { get; set; }
        public int skipped { get; set; }
        public System.DateTime starttime { get; set; }
        public System.DateTime endtime { get; set; }
        public double duration { get; set; }
    }
}
