//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace Automation.Gui.Models
{
    public partial class setting
    {
        public int id { get; set; }

        [StringLength(50)]
        public string targetBrowser { get; set; }

        [StringLength(50)]
        public string operatingSystem { get; set; }

        [StringLength(100)]
        public string seleniumHubUri { get; set; }

        [StringLength(100)]
        public string screenshotFolder { get; set; }

        public sbyte isActive { get; set; }
    }
}
