//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.XmlWriter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class setting
    {
        public int id { get; set; }
        public string targetBrowser { get; set; }
        public string operatingSystem { get; set; }
        public string seleniumHubUri { get; set; }
        public string screenshotFolder { get; set; }
        public sbyte isActive { get; set; }
    }
}
